import { ConfigDashboard } from "@/components/config-dashboard"

export default function Page() {
  return (
    <main className="min-h-screen bg-slate-50 p-4 md:p-8 font-sans">
      <div className="max-w-7xl mx-auto space-y-8">
        <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-slate-200">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold text-slate-900 tracking-tight">
              Discord Forwarder Config
            </h1>
            <p className="text-slate-500 mt-1 text-sm md:text-base">
              可视化配置生成器 · 轻松管理转发规则
            </p>
          </div>
          <div className="flex items-center gap-2 text-sm text-slate-500 bg-white px-3 py-1.5 rounded-full border border-slate-200 shadow-sm">
            <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
            本地自动保存中
          </div>
        </header>

        <ConfigDashboard />
        
        <footer className="text-center text-slate-400 text-xs py-8">
          <p>Generated by v0 · Secure Client-Side Processing</p>
        </footer>
      </div>
    </main>
  )
}
